[traces] change voltage trigger level
* Changed max voltage test to skip the file instead of exiting
* Changed the trigger voltage, this leads to an exception in file 6

```
File name: 6.txt
--
Traceback (most recent call last):
  File "parse_traces.py", line 159, in <module>
      off_time_sample = above_threshold_on_time_sample_list[count] +
      above_threshold_duration_samples_list[count]
      IndexError: list index out of range
```

Committed for documentation